---
all:
  hosts:
    devops_stage4_server:
      ansible_host: 172.191.20.186
      ansible_user: kefaslungu
      ansible_ssh_private_key_file: /home/kefaslungu/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
